/var/spool/slurmd/job1054975/slurm_script: line 17: conda: command not found
/var/spool/slurmd/job1054975/slurm_script: line 19: conda: command not found
/var/spool/slurmd/job1054975/slurm_script: line 26: conda: command not found
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14d431024f10>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/datetime/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14d431024c70>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/datetime/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14d4310246d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/datetime/
slurmstepd: error: *** JOB 1054975 ON r6i1n8 CANCELLED AT 2024-07-30T15:48:57 ***
