
CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Loading pytorch-gpu/py3/1.12.1
  Loading requirement: cuda/11.2 nccl/2.9.6-1-cuda cudnn/8.1.1.33-cuda gcc/8.5.0
    openmpi/4.1.1-cuda intel-mkl/2020.4 magma/2.5.4-cuda-oneapi-mkl sox/14.4.2
    sparsehash/2.0.3 libjpeg-turbo/2.1.3
+ pip install -r requirements.txt
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14743f84c100>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/datetime/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14743f84c430>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/datetime/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x14743f84c5e0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/datetime/
slurmstepd: error: *** JOB 1041284 ON r3i4n8 CANCELLED AT 2024-07-29T15:19:44 ***
